apiVersion: v1
kind: PersistentVolume
metadata:
   name: influxdb-pv
   labels:
     store: influxdb-disk
spec:
   capacity:
     storage: 2Gi
   accessModes:
   - ReadWriteMany
   persistentVolumeReclaimPolicy: Retain
   nfs:
      server: 10.1.2.17
      path: "/mnt/influxdb"
