kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: influxdb-storage
spec:
   accessModes:
   - ReadWriteMany
   resources:
     requests:
       storage: 2Gi
   selector:
     matchLabels:
       store: influxdb-disk
