kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: grafana-pvc
spec:
   accessModes:
   - ReadWriteMany
   resources:
     requests:
       storage: 2Gi
   selector:
      matchLabels:
         store: grafana-disk
