apiVersion: v1
kind: PersistentVolume
metadata:
   name: grafana-storage
spec:
   capacity:
     storage: 2Gi
   accessModes:
   - ReadWriteMany
   nfs:
      server: 10.1.2.17
      path: "/mnt/grafana"
