apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: grafana-deploy
  labels:
    task: grafana-dashboard
spec:
  replicas: 1
  template:
    metadata:
      labels:
        task: grafana-dashboard
    spec:
      volumes:
      - name: grafana-pod-storage
        persistentVolumeClaim:
          claimName: grafana-pvc
      securityContext:
        fsGroup: 65534
      containers:
      - name: grafana
        image: grafana/grafana
        volumeMounts:
        - name: grafana-pod-storage
          mountPath: /var
        ports:
          - containerPort: 3000
            protocol: TCP
        env:
        - name: INFLUXDB_HOST
          value: monitoring-influxdb
        - name: GRAFANA_PORT
          value: "3000"
        - name: GF_AUTH_BASIC_ENABLED
          value: "false"
        - name: GF_AUTH_ANONYMOUS_ENABLED
          value: "true"
        - name: GF_AUTH_ANONYMOUS_ORG_ROLE
          value: Admin
        - name: GF_SERVER_ROOT_URL
          value: /
