apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: grafana-deploy
spec:
  replicas: 1
  template:
    metadata:
      labels:
        task: grafana-dashboard
    spec:
      volumes:
      - name: grafana-storage-pvc
        persistentVolumeClaim:
          claimName: grafana-storage
      containers:
      - name: grafana
        image: grafana/grafana
        ports:
          - containerPort: 3000
            protocol: TCP
        volumeMounts:
        - name: grafana-storage-pvc
          mountPath: /var
        env:
        - name: INFLUXDB_HOST
          value: monitoring-influxdb
        - name: GRAFANA_PORT
          value: "3000"
        - name: GF_AUTH_BASIC_ENABLED
          value: "false"
        - name: GF_AUTH_ANONYMOUS_ENABLED
          value: "true"
        - name: GF_AUTH_ANONYMOUS_ORG_ROLE
          value: Admin
        - name: GF_SERVER_ROOT_URL
          # value: /api/v1/proxy/namespaces/kube-system/services/monitoring-grafana/
          value: /
