apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: influxdb-deploy
  labels:
    task: dashboard
spec:
  replicas: 1
  template:
    metadata:
      labels:
        task: dashboard
    spec:
      volumes:
      - name: influxdb-storage-pd
        persistentVolumeClaim:
          claimName: influxdb-storage
      containers:
      - name: influxdb
        image: library/influxdb
        securityContext:
          fsGroup: 65534
        ports:
        - containerPort: 8083
          hostPort: 8083
        - containerPort: 8086
          hostPort: 8086
        securityContext:
           runAsUser: 65534
        volumeMounts:
        - name: influxdb-storage-pd
          mountPath: /var/lib/influxdb
        env:
        - name: INFLUXDB_GRAPHITE_ENABLED
          value: "true"
        - name: INFLUXDB_ADMIN_ENABLED
          value: "true"
        - name: INFLUXDB_DATA_DIR
          value: "/var/lib/influxdb/data"
        - name: INFLUXDB_COLLECTD_TYPESDB
          value: "/var/lib/"
