apiVersion: v1
kind: Service
metadata:
  name: influxdb-service
spec:
  type: NodePort
  ports:
  - name: api
    port: 8086
    targetPort: 8086
  - name: admin-portal
    port: 8083
    targetPort: 8083
  selector:
    task: dashboard
