apiVersion: v1
kind: Service
metadata:
  labels:
    name: ntopng-service
    role: ntopng-service
  name: ntopng-srv
spec:
  type: NodePort
  ports:
    - port: 3000
      targetPort: 3000
  selector:
    name: ntopng
