kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: redis-pvc
spec:
   accessModes:
   - ReadWriteMany
   resources:
     requests:
       storage: 2Gi
   selector:
     matchLabels:
       store: redis-disk
