apiVersion: v1
kind: PersistentVolume
metadata:
   name: redis-pv
   labels:
     store: redis-disk
spec:
   capacity:
     storage: 2Gi
   accessModes:
   - ReadWriteMany
   persistentVolumeReclaimPolicy: Retain
   nfs:
      server: 10.1.2.17
      path: "/mnt/redis"
